# -*- coding: utf-8 -*-
"""significance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CEBlDm_tfMgpiOHaKIbECSyqfIT-XXwD
"""

import numpy as np
from scipy.stats import ranksums
rng = np.random.default_rng()
sample1 = [0,0,0,1,1,0,1,0,0,0]
sample2 = [1,1,1,1,1,1,1,1,1,1] # a shifted distribution
ranksums(sample2, sample1)

sample1

import pickle

import numpy as np
pred_224_us=np.load("/content/drive/MyDrive/Bayezid sir/residue_level/database/amino_acid_analysis/pdna_224.npy")
pred_316_us=np.load("/content/drive/MyDrive/Bayezid sir/residue_level/database/amino_acid_analysis/pdna_316.npy")
pred_543_us=np.load("/content/drive/MyDrive/Bayezid sir/residue_level/database/amino_acid_analysis/pdna_543.npy")

#importing files
seq= open("/content/drive/MyDrive/Bayezid sir/residue_level/database/amino_acid_analysis/iprodna/Copy of pdna316_label.txt", "r")
count=0
protein_list=[]
c=0
for x in seq:
    
    if(count%2==1):
        
      x=x.replace('\n','')
      protein_list.append(x)
    count+=1

c=0
us_316_list=[]
start=0
for item in protein_list:
  l=len(item)
  a=pred_316_us[start:start+l]
  if(a.shape[0]>93):
    b=a[0:92]
  else:
    b=a
  us_316_list.append(b.tolist())
  start=start+l

  


us_316_done=[]
c=0
for i in us_316_list:
  c+=1
  if(c==21):
    break
  for r in i:
    us_316_done.append(r)


import pickle
with open("/content/drive/MyDrive/Bayezid sir/residue_level/database/label_316_iprodna_significance", "rb") as fp:   # Unpickling
  ipro_316_done = pickle.load(fp)

ranksums(us_316_done, ipro_316_done)

#importing files
seq= open("/content/drive/MyDrive/Bayezid sir/residue_level/database/amino_acid_analysis/iprodna/Copy of PDNA543_label.txt", "r")
count=0
protein_list=[]
c=0
for x in seq:
    
    if(count%2==1):
        
      x=x.replace('\n','')
      protein_list.append(x)
    count+=1

c=0
us_543_list=[]
start=0
for item in protein_list:
  l=len(item)
  a=pred_543_us[start:start+l]
  if(a.shape[0]>93):
    b=a[0:92]
  else:
    b=a
  us_543_list.append(b.tolist())
  start=start+l

  


us_543_done=[]
c=0
for i in us_543_list:
  c+=1
  if(c==16):
    break
  for r in i:
    us_543_done.append(r)


import pickle
with open("/content/drive/MyDrive/Bayezid sir/residue_level/database/label_543_iprodna_significance", "rb") as fp:   # Unpickling
  ipro_543_done = pickle.load(fp)

ranksums(us_543_done, ipro_543_done)

#importing files
seq= open("/content/drive/MyDrive/Bayezid sir/residue_level/database/amino_acid_analysis/iprodna/Copy of pdna224.txt", "r")
count=0
protein_list=[]
c=0
for x in seq:
    
    if(count%3==2):
        
      x=x.replace('\n','')
      protein_list.append(x)
    count+=1

c=0
us_224_list=[]
start=0
for item in protein_list:
  l=len(item)
  a=pred_224_us[start:start+l]
  if(a.shape[0]>93):
    b=a[0:92]
  else:
    b=a
  us_224_list.append(b.tolist())
  start=start+l

  


us_224_done=[]
c=0
for i in us_224_list:
  c+=1
  if(c==13):
    break
  for r in i:
    us_224_done.append(r)


import pickle
with open("/content/drive/MyDrive/Bayezid sir/residue_level/database/label_224_iprodna_significance", "rb") as fp:   # Unpickling
  ipro_224_done = pickle.load(fp)

ranksums(us_224_done, ipro_224_done)